---
title: "hw6"
author: "Ty Darnell"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message=F,warning=F)
```

```{r,echo=F}
library(tidyverse)
library(pracma)
library(data.table)
library(matlib)
library(knitr)
library(psych)
library(nlme)
library(reshape2)
```

```{r}
dat=fread("cholesterol.dat")
dat=dat%>%mutate(group= factor(group,levels = 1:2, labels = c("T", "C")),id=factor(id))%>%rename(y0=y1,y1=y2,y2=y3,y3=y4,y4=y5)
treat=dat%>%filter(group=="T")
control=dat%>%filter(group=="C")
treaty=treat%>%select(y0,y1,y2,y3,y4)
controly=control%>%select(y0,y1,y2,y3,y4)
```

```{r}
sigmat= var(treaty, na.rm = TRUE)
sigmac= var(controly, na.rm = TRUE)
cort=cor(treaty, use = "pairwise.complete.obs")
corc=cor(controly, use = "pairwise.complete.obs")
```

```{r}
meant=colMeans(treaty,na.rm=T)
meanc=colMeans(controly,na.rm=T)
mut=as.vector(meant)
muc=as.vector(meanc)
```



```{r}
pairs.panels(treaty)
```

```{r}
plot(meant, type = "b", xlab = "time", ylab = "y", col = "blue",lty=1,ylim = range(c(meanc, meant)))
points(meanc, type = "b", col = "red",lty=2)
legend("bottomright", legend = c("treatment","control"), col = c("blue","red"),lty=c(1,2), pch = 21)
```
```{r}
m=rep(c(0,6,12,20,24),2)
mu=c(muc,mut)
group=c(rep(1,5),rep(2,5))
d=as_tibble(cbind(m,mu,group))
d$group=factor(d$group)
ggplot(data=d,aes(x=m,y=mu,group=group))+geom_point()+geom_line(aes(linetype=group,color=group))
```

```{r}
u=muc[1]
b2=muc[2]-u
b3=muc[3]-u
b4=muc[4]-u
b5=muc[5]-u
b=c(0,b2,b3,b4,b5)
a2=mut[1]-u
g22=mut[2]-u-b2
g23=mut[3]-u-b3
g24=mut[4]-u-b4
g25=mut[5]-u-b5
g=c(0,g22,g23,g24,g25)
```

```{r}
datl <- melt(dat,
id.vars = c("id","group"),
measure.vars = c("y0","y1","y2","y3","y4"),
variable.name = "time",
value.name = "y")
```

```{r}
datl$group <- relevel(datl$group,"C")
datl$time <- relevel(datl$time,"y0")
```

```{r}
e.lme <- lme(y ∼ group*time,random =∼1|id,data = datl, na.action = na.omit)
logLik(e.lme)
```

```{r}
e.gls <- gls(y ∼ group*time, correlation = corCompSymm(form =∼ 1|id), data = datl, na.action = na.omit)
logLik(e.gls)
```

```{r}
index.baseline <- which(datl$time=="y0")
```

```{r}
index.t <- base::setdiff(which(datl$group=="T"), index.baseline)
```

```{r}
index.c <- base::setdiff(which(datl$group=="C"), index.baseline)
```

```{r}
pval=function(z){
  2*pnorm(-abs(z))
}
```

