---
title: "Football663"
author: "Ty Darnell"
date: "4/12/2019"
output:
  prettydoc::html_pretty:
     theme: cayman
     df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F,message=F,warning=F)
```

```{r,echo=F}
library(knitr)
library(tidyverse)
library(data.table)
library(linmod)
library(magrittr)
library(ggfortify)
library(matlib)
library(RColorBrewer)
```

```{r,echo=F}
source('rain_cloud_func.R')
```

LAA = Raiders
LAN = Rams

```{r}
fb=fread('fb.csv')
cols <- c("ha","year","day","ot")
fb %<>% mutate_each_(funs(factor(.)),cols)
```

```{r}
fb1=fb%>%mutate(ptdiff=favpts-undpts,favwin=tf(ptdiff>0),night=tf(day%in%c("N","M","H")),diffout=ptdiff-pts,absdiffout=abs(diffout))%>%rename(spread=pts)
fb1=fb1%>%mutate(cover=tf(ptdiff>spread))
```


```{r}
predwinpct=sum(fb1$favwin==1)/672
teams=unique(c(fb1$fav,fb1$und))
```


```{r}
favcovpct=fb1%>%group_by(fav)%>%summarise(favcovpct=mean(cover==1))%>%arrange(desc(favcovpct))%>%rename(team=fav)
undcovpct=fb1%>%group_by(und)%>%summarise(undcovpct=mean(cover==0))%>%arrange(desc(undcovpct))%>%rename(team=und)
coverpct=left_join(favcovpct,undcovpct)
coverpct=coverpct%>%mutate(avgcov=(favcovpct+undcovpct)/2)%>%arrange(desc(avgcov))
```


```{r,echo=T}
coverpct
```

```{r}
afceast=c("BUF","IND","MIA","NE","NYJ")

afccentral=c("CLE","HOU","PIT","CIN")

afcwest=c("DEN","KC","LAA","SEA","SD")

nfceast=c("NYG","PHA","WAS","PHX","DAL")

nfccentral=c("MIN","GB","DET","CHI","TB")
nfcwest=c("SF","LAN","NO","ATL")
```


```{r}
divisions=list(afceast,afccentral,afcwest,nfceast,nfccentral,nfcwest)

names(divisions)=c("afceast","afccentral","afcwest","nfceast","nfccentral","nfcwest")
divs=c("afceast","afccentral","afcwest","nfceast","nfccentral","nfcwest")
nfc=c(nfccentral,nfceast,nfcwest)
afc=c(afccentral,afceast,afcwest)
```

```{r}
a=list()
for (i in seq_along(divisions)) {
a[[i]]=fb1%>%filter(fav%in%divisions[[i]]&und%in%divisions[[i]])%>%mutate(div=divs[i])
}
divgames=map_df(a,as_tibble)
```


```{r}
divgames=divgames%>%mutate(divgame=1)
fb2=right_join(divgames,fb1)
fb2$divgame[is.na(fb2$divgame)]=0
fb2$div[is.na(fb2$div)]="non"
fb2$divgame=factor(fb2$divgame)
fb2$div=factor(fb2$div)
```

```{r}
ggplot(data=fb2,aes(y=diffout,group=div))+geom_boxplot(aes(color=div))
```

```{r}
ggplot(data=fb2,aes(div,diffout))+geom_violin(aes(color=div))
```

```{r}
rain_cloud(fb2,fb2$div,fb2$diffout)
```

```{r}
nondiv=fb2%>%filter(divgame==0)
```

```{r}
rain_cloud(fb2,fb2$divgame,fb2$diffout)
```
```{r}
div2=divisions
div2$afccentral[5]="empty"
div2$nfcwest[5]="empty"
div3=as_tibble(div2)
```

```{r}
nondiv=nondiv%>%mutate(favdiv=case_when(fav%in%div3$afceast~"afceast",fav%in%div3$afcwest~"afcwest",fav%in%div3$afccentral~"afccentral",fav%in%div3$nfceast~"nfceast",fav%in%div3$nfccentral~"nfccentral",fav%in%div3$nfcwest~"nfcwest"))

nondiv=nondiv%>%mutate(unddiv=case_when(und%in%div3$afceast~"afceast",und%in%div3$afcwest~"afcwest",und%in%div3$afccentral~"afccentral",und%in%div3$nfceast~"nfceast",und%in%div3$nfccentral~"nfccentral",und%in%div3$nfcwest~"nfcwest"))
non89=nondiv%>%filter(year==89)
```


```{r}
b=list()
for (i in seq_along(divs)) {
b[[i]]=non89%>%filter(favdiv==divs[[i]]|unddiv==divs[[i]])%>%mutate(divname=divs[[i]])
}
divs2=map_df(b,as_tibble)
divs2$divname=factor(divs2$divname)
meandivs=divs2%>%group_by(divname)%>%summarise(meandiv=mean(diffout))
```


```{r,echo=T}
anova(aov(diffout~divname,divs2))
```


```{r}
byteams=list()
for (i in seq_along(teams)) {
  byteams[[i]]=filter(fb2,fav==as.character(teams[i])|und==as.character(teams[i]))%>%mutate(team=teams[i])
}
byteams=map_df(byteams,as_tibble)
byteams$team=factor(byteams$team)
```


```{r}
team89=byteams%>%filter(year==89)
teammeans89=team89%>%group_by(team)%>%summarise(teammean=mean(diffout))
team90=byteams%>%filter(year==90)
teammeans90=team90%>%group_by(team)%>%summarise(teammean=mean(diffout))
team2=byteams%>%filter(year==89|year==90)
```


```{r,echo=T}
anova(aov(diffout~team,team89))
```

```{r,echo=T}
anova(aov(diffout~year,fb2))
```

```{r,echo=T}
anova(aov(diffout~divgame,fb2))
```
```{r}
wk10=team89%>%filter(wk<=10)
wkend=team89%>%filter(wk>10)
```


```{r}
fav10=wk10%>%group_by(team)%>%filter(fav==team)%>%summarise(favsum=sum(favpts))
und10=wk10%>%group_by(team)%>%filter(und==team)%>%summarise(undsum=sum(undpts))
pts10=left_join(und10,fav10)
pts10=pts10%>%mutate_all(~replace(., is.na(.), 0))
pts10=pts10%>%mutate(ptsfor=undsum+favsum)%>%select(team,ptsfor)
```

for each team: Total points for , total points against, opponents total pts for, total opponent pts against
and spread (if fave, positive, if underdog, negative)

```{r}
fava=wk10%>%group_by(team)%>%filter(fav!=team)%>%summarise(favsum=sum(favpts))
unda=wk10%>%group_by(team)%>%filter(und!=team)%>%summarise(undsum=sum(undpts))
ptsa=left_join(fava,unda)
ptsa%<>%mutate_all(~replace(., is.na(.), 0))
ptsa=ptsa%>%mutate(ptsagt=undsum+favsum)%>%select(team,ptsagt)
ptsfa=left_join(pts10,ptsa)
```


```{r}
fb3=byteams%>%filter(year==89&wk<12)
fb3%<>%group_by(wk)%>%mutate(k=case_when(und==team~-1,und!=team~1),spread=k*spread,l=as.numeric(fav==team),m=as.numeric(und==team))%>%select(c(team,wk,favpts,undpts,spread,fav,und,ptdiff,diffout,cover,div,k,l,m))
```


```{r}
fb3%<>%mutate(ptsfor=favpts*l+undpts*m,ptsagt=favpts*m+undpts*l)
fb3%<>%mutate(ptdiff=ptsfor-ptsagt)
```

```{r}
fb3%<>%group_by(team)%>%mutate(avgdiff1=cumsum(ptdiff)/wk,avgdiff=lag(avgdiff1))
fb3%<>%mutate(opp=case_when(l==1~und,l==0~fav))
fb3%<>%mutate(diffout1=k*diffout,cover=as.numeric(diffout>=0))
```

```{r}
fb4=fb3%>%select(c(wk,team,opp,spread,avgdiff,cover))
```



```{r}
test=fb4 %>% 
  unite(vs, team, opp, sep = "-",remove=F)
test%<>%unite(vs2,opp,team,sep="-",remove=F)
test1=test%>%select(-vs2)%>%rename(team1=team,avgdiff1=avgdiff)
test2=test%>%select(-vs)%>%rename(vs=vs2,team2=team,avgdiff2=avgdiff)
fb5=left_join(test1,test2,by=c("wk","vs"))
fb5%<>%select(wk,vs,team1,spread.x,avgdiff1,team2,avgdiff2,cover.x)%>%rename(spread=spread.x,cover1=cover.x)
fb5%<>%filter(wk!=1)
```


```{r}
fb89=fb2%>%filter(year==89&wk<11)
fb89%>%group_by(wk)%>%summarise(med=median(diffout,na.rm=T))
```

all weeks for model

```{r}
allwks=byteams%>%filter(year==89)
allwks%<>%group_by(wk)%>%mutate(k=case_when(und==team~-1,und!=team~1),spread=k*spread,l=as.numeric(fav==team),m=as.numeric(und==team))%>%select(c(team,wk,favpts,undpts,spread,fav,und,ptdiff,diffout,cover,div,k,l,m))
```


```{r}
allwks%<>%mutate(ptsfor=favpts*l+undpts*m,ptsagt=favpts*m+undpts*l)
allwks%<>%mutate(ptdiff=ptsfor-ptsagt)
```

```{r}
allwks%<>%group_by(team)%>%mutate(avgdiff1=cumsum(ptdiff)/wk,avgdiff=lag(avgdiff1))
allwks%<>%mutate(opp=case_when(l==1~und,l==0~fav))
allwks%<>%mutate(diffout1=k*diffout,cover=as.numeric(diffout>=0))
```

```{r}
allwks2=allwks%>%select(c(wk,team,opp,spread,avgdiff,cover))
```


```{r}
testw=allwks2 %>% 
  unite(vs, team, opp, sep = "-",remove=F)
testw%<>%unite(vs2,opp,team,sep="-",remove=F)
testw1=testw%>%select(-vs2)%>%rename(team1=team,avgdiff1=avgdiff)
testw2=testw%>%select(-vs)%>%rename(vs=vs2,team2=team,avgdiff2=avgdiff)
fball=left_join(testw1,testw2,by=c("wk","vs"))
fball%<>%select(wk,vs,team1,spread.x,avgdiff1,team2,avgdiff2,cover.x)%>%rename(spread=spread.x,cover1=cover.x)
fball%<>%filter(wk!=1)
```


```{r}
dflist=list()
for (i in 1:6) {
  dflist[[i]]=filter(fball,wk<=10+i)
}
```

