---
title: "667exam"
author: "Ty Darnell"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning=F,message=F)
```

```{r}
library(tidyverse)
library(knitr)
library(matlib)
library(pracma)
library(data.table)
```

```{r}
var3=function(mc,v1,v2,v3,c12,c13,c23,a,b,c){
var=a^2*v1+b^2*v2+c^2*v3
var=mc*var
cv=mc*2*(a*b*c12+a*c*c13+b*c*c23)
v=var+cv
paste("var=",v,"covpart=",cv,"vpart=",var)
}
```

```{r}
vcmat3=function(v,c12,c13,c23,scale=1){
x=matrix(rep(v,9),nrow=3)
x[upper.tri(x)]=c(c12,c13,c23)
x[lower.tri(x)]=c(c12,c13,c23)
x=scale*x
return(x)
}
```

```{r}
varmat3=function(mat,c1,c2,c3){
v=mat[1,1]
c12=mat[1,2]
c13=mat[1,3]
c23=mat[2,3]
cov=c2*c12+c3*c13+c1*v
return(cov)
}

```

```{r}
a1=function(y1,y2,y3,c1,c2,c3) c1*y1+c2*y2+c3*y3
a=function(y1,y2,y3) .5*(y2+y3)-y1
x=vcmat3(1,.5,.3,.4,50)
a(x[1,1],x[1,2],x[1,3])
```

```{r}
vcov3=function(c1,c2,c3,mat){
v=mat[1,1]
c12=mat[1,2]
c13=mat[1,3]
c23=mat[2,3]
cov=c2*c12+c3*c13+c1*v
var=(c1^2+c2^2+c3^2)*v+2*(c1*c2*c12+c1*c3*c13+c2*c3*c23)
paste("var=",var,"cov=",cov)
}
```

