---
title: "data3 appendix"
author: "Ty Darnell"
date: "4/17/2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message=F,warning=F)
library(tidyverse)
library(knitr)
library(readxl)
```


```{r}
etable=function(exposure,disease){
  t=table(exposure,disease)[2:1,2:1]
  rownames(t)=c('E+','E-')
  colnames(t)=c('D+','D-')
  kable(t)
}

riskratio=function(a,b,c,d){
  e=a/(a+b)
  f=c/(c+d)
  c(e,f,e/f)
}

ciriskr=function(ecases,enoncases,uecases,uenoncases){
  a=ecases
  b=enoncases
  c=uecases
  d=uenoncases
  e=a/(a+b)
  f=c/(c+d)
  rr=e/f
  z=c(-1.96,1.96)
  se=sqrt(1/a-1/(a+b)+
            1/c-1/(c+d))
  ci=exp(log(rr)+z*se)
  c("Risk Ratio"=rr,"95 CI"=ci)
}

rateratio=function(cases,noncases,pyrcases,pyrnoncases){
  a=cases
  b=noncases
  p=pyrcases
  q=pyrnoncases
  (a/p)/(b/q)
}

cirater=function(cases,noncases,pyrcases,pyrnoncases){
  a=cases
  b=noncases
  p=pyrcases
  q=pyrnoncases
  rr=(a/p)/(b/q)
  se=sqrt(1/a+1/b)
  z=c(-1.96,1.96)
  ci=exp(log(rr)+z*se)
  c("Rate Ratio"=rr,"95 CI"=ci)
}

cioddsr=function(ecases,enoncases,uecases,uenoncases){
  a=ecases
  b=enoncases
  c=uecases
  d=uenoncases
  or=(a/c)*(d/b)
  se=sqrt(1/a+1/b+1/c+1/d)
  z=c(-1.96,1.96)
  ci=exp(log(or)+z*se)
  c("Odds Ratio"=or,"95 CI"=ci)
}
```


```{r}
cc <- read_excel("casecontrol.xlsx")
```

```{r}
ctab=etable(cc$VIRUS,cc$CANCER)

```

```{r}
men=cc%>%filter(SEX==0)
women=cc%>%filter(SEX==1)
mtab=etable(men$VIRUS,men$CANCER)
wtab=etable(women$VIRUS,women$CANCER)
mtab
wtab
```


```{r}
cOR=4.22
y = glm(CANCER ~ VIRUS+SEX, family=binomial,data = cc)
(a=round(exp(cbind(coef(y), confint(y))),digits=2))
aOR=a["VIRUS",1]
pchange1=(cOR-aOR)/cOR
round(pchange1,digits=2)
```


```{r}
x = glm(CANCER ~ VIRUS+RACE, family=binomial,data = cc)
round(exp(cbind(coef(x), confint(x))),digits=2) 
pchange2=(cOR-3.67)/cOR
round(pchange2,digits=2)
```


